import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import Providers from "@/providers/TanstackProvider";
import { cache } from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  const queryClient = cache(() => new QueryClient({
    defaultOptions: {
      queries: {
        refetchInterval: 10000,
        staleTime: 5000
      }
    }
  })); 
  const dehydratedState = dehydrate(queryClient());

  return (
    <html>
      <body>
          <Providers>
            <HydrationBoundary state={dehydratedState} >
               {children}
            </HydrationBoundary>
            <ReactQueryDevtools initialIsOpen={false}/>
          </Providers>
      </body>
    </html>
  )
}
